---
- name: Install Github cli
  pacman:
    name: github-cli
    state: present
  become: yes

- name: Retrieve Git Credentials From Vault
  ansible.builtin.include_vars:
    file: ../vault/git_credentials.yml
    name: git_credentials
  no_log: true # Don't display email in logs

- name: Set Github Personal Access Token
  ansible.builtin.shell: |
    gh auth login --with-token "{{ git_credentials.git_token }}"
  environment:
    GITHUB_TOKEN: "{{ git_credentials.git_token }}"

- name: Configure GitHub CLI to USE HTTPS
  ansible.builtin.shell: |
    gh config set git_protocol https
