---
  - name: Change directory and make/install yay
    become_user: "{{ ansible_user }}"
    shell: |
      cd ~/yay-git
      makepkg -si --noconfirm
      cd ~/repos/ansible
    when: ansible_distribution == "Archlinux"

  - name: Update yay package cache
    ansible.builtin.command: yay -Sy
    when: ansible_distribution == "Archlinux"

  - name: Install essential yay packages
    ansible.builtin.command: yay -S --needed --nonconfirm "{{ item }}"
    loop:
      ## Base
      - pfetch
      - xdotool
      - bluez-utils-compat
      - spotify
      - brave-bin
      - imv-git
      - slack-desktop
      - ttf-jetbrains-mono-nerd
      - ttf-sourcecodepro-nerd
      - dracula-gtk-theme
      # screenshot
      - grim-git
      - slurp-git
      # desktop env
      - octopi
      - bibata-cursor-theme
      - lxsession-git
      - wleave-git
      - timeshift
      - swaylock
      - swww-git
      - nnn-nerd
      # virualization
      - kvritual
      - qemu-git
      # dev
      - lazygit-git
      - lazydocker
      - doxygen-git
      - jetbrains-toolbox
      # game engine
      - unityhub
      #- unreal-engine
      #- godot-git
      #- godot3
    tags:
      - complete-arch
      - core-arch
    when: ansible_distribution == "Archlinux"

  - name: Set default shell to zsh
    user:
      name: "{{ ansible_user }}"
      shell: /bin/zsh
