
---
- name: Install entertainment tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    ## Entertainment:
    - vlc
    - discord
    - spotify
    - mpv # Media player
    - yewtube # Command-line YouTube browser/player
    - cava # Console-based audio visualizer
  tags:
    - complete
    - entertainment

- name: Install gaming tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    #gaming
    - lutris
    - steam
    - wine
    - mangohud
  tags:
    - complete
    - gaming
