
---
- name: Install entertainment tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    ## Entertainment:
    - vlc
    - discord
    - mpv # Media player
    - cava # Console-based audio visualizer
  tags:
    - complete-arch
    - complete-deb
    - entertainment

- name: Install gaming tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    #gaming
    - lutris
    - steam
    - wine
    - mangohud
  tags:
    - complete-arch
    - complete-deb
    - gaming
