---
  - name: Change directory and stow
    become_user: "{{ ansible_user }}"
    shell: |
      cd ~/.config
      rm -dfr nvim btop dunst hypr kitty tmux waybar
      cd ~/.dotfiles
      stow -t ~/ -R neovim
      stow -t ~/ -R scripts
      stow -t ~/ -R tmux
      stow -t ~/ -R shell
      stow -t ~/ -R waybar
      stow -t ~/ -R hyprland
      stow -t ~/ -R kitty
      stow -t ~/ -R starship
      stow -t ~/ -R btop
