---
- name: Basic Setup
  hosts: personal
  become: yes

  tasks:
    - name: Update package cache
      pacman:
        update_cache:yes

    - name: Install essential packages
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ default_shell }}"
        - "{{ default_term_emulator }}"
        - ranger
        - rofi
        - wl-clipboard
        - sway
        - swww
        - swaylock
        - swayidle
        - waybar
        - "{{ default_text_editor }}"
        - vlc
        - feh
        - htop
        - btop
        - pipewire
        - fontconfig
        - tlp
        - lxappearance
        - spotify
        - discord
        - stow
        - git
        - gh
        - dolphin
        - fzf
        - yay

    - name: Set default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
