---
- name: Basic Setup
  hosts: personal
  become: yes
  roles:
    - ~/repos/ansible/roles/git
    - ~/repos/ansible/roles/gh-cli

  tasks:
    - name: Update package cache
      pacman:
        update_cache: yes

    - name: Install essential packages
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - pacman-contrib
        - "{{ default_shell }}"
        - "{{ default_term_emulator }}"
        - ranger
        - rofi
        - wl-clipboard
        - waybar
        - "{{ default_text_editor }}" # neovim btw ;)
        - vlc
        - htop
        - btop
        - pipewire
        - fontconfig
        - tlp
        - lxappearance
        - discord
        - stow
        - dolphin
        - fzf
        - nitrogen
        - dunst
        - starship
        - mpv
        - freerdp
        - xfce4-power-manager
        - mousepad
        - ttf-font-awesome
        - ttf-fira-sans
        - ttf-fira-code
        - ttf-firacode-nerd
        - figlet
        - breeze
        - breeze-gtk
        - exa
        - python-pipx
        - python-psutil
        - python-rich
        - python-click
        - xdg-desktop-portal-gtk
        - pavucontrol
        - tumbler
        - xautolock
        - blueman
        - python-pywal
        - swww
        - zoxide
        - tmux
        - bluez-utils-compat

    - name: Clone yay repo
      git:
        repo: https://aur.archlinux.org/yay-git.git
        dest: ~/yay-git
        update: yes
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"
      notify: Change directory and make/install yay

  handlers:
    - name: Change directory and make/install yay
      become_user: "{{ ansible_user }}"
      shell: |
        cd ~/yay-git
        makepkg -si
        cd ~/repos/ansible

    - name: Update yay package cache
      ansible.builtin.command: yay -Sy

    - name: Install essential yay packages
      ansible.builtin.command: yay -S --needed --nonconfirm "{{ item }}"
      loop:
        - spotify
        - brave-bin
        - pfetch
        - bibata-cursor-theme
        - wleave-git
        - timeshift
        - swaylock

    - name: Set default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
