---
- name: Basic Setup
  hosts: personal
  become: yes

  tasks:
    - name: Update package cache
      pacman:
        update_cache:yes

    - name: Install essential packages
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ default_shell }}"
        - "{{ default_term_emulator }}"
        - ranger
        - rofi
        - wl-clipboard
        - waybar
        - "{{ default_text_editor }}" # neovim btw ;)
        - vlc
        - feh
        - htop
        - btop
        - pipewire
        - fontconfig
        - tlp
        - lxappearance
        - spotify
        - discord
        - stow
        - gh
        - dolphin
        - fzf

        - pacman-contrib
        - nitrogen
        - dunst
        - starship
        - mpv
        - freerdp
        - xfce4-power-manager
        - thunar
        - mousepad
        - ttf-font-awesome
        - ttf-fira-sans
        - ttf-fira-code
        - ttf-firacode-nerd
        - figlet
        - breeze
        - breeze-gtk
        - exa
        - python-pipx
        - python-psutil
        - python-rich
        - python-click
        - xdg-desktop-porta-gtk
        - pavucontrol
        - tumbler
        - xautolock
        - blueman
        - nautilus





    - name: Set default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh
