---
- name: Configure Dotfiles
  hosts: personal
  become: yes
  roles:
    - ~/repos/ansible/roles/git
    - ~/repos/ansible/roles/gh-cli
  tasks:
    - name: Clone .dotfiles repo
      git:
        repo: https://github.com/Nordin-S/dotfiles.git
        dest: ~/.dotfiles
        update: yes
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"
      notify: Change directory and stow

    - name: Clone tmux pakage manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"

  handlers:
    - name: Change directory and stow
      become_user: "{{ ansible_user }}"
      shell: |
        cd ~/.dotfiles
        stow -t ~/ -R neovim
        stow -t ~/ -R scripts
        stow -t ~/ -R tmux
        stow -t ~/ -R .zshrc
        stow -t ~/ -R waybar
        stow -t ~/ -R hyprland
        stow -t ~/ -R kitty
